/**
 * 球员英文名 → 中文译名 字典 + 查询函数。
 *
 * 背景:API-Football 不同端点返回的球员名形态不一致:
 *  - /players/topscorers、/topassists:混用缩写名(`L. Messi`、`O. Dembélé`)与全名(`Kylian Mbappé`)。
 *  - /fixtures/players(球员评分):多为带变音符的全名(`Arda Güler`、`Hakan Çalhanoğlu`)。
 * 为吸收这些差异,字典 key 一律用「归一化名」存储,查询时对输入做同样归一化后再查。
 *
 * 归一化规则(normalizeName):
 *  1. Unicode NFD 拆分 + 去掉组合用变音符(̀-ͯ),如 é→e、ö→o、ğ→g、ı→i、ç→c、ø→o(见下注)。
 *  2. 去掉所有 `.`(缩写点);连字符 `-` 视作空格(`Son Heung-min`→`son heung min`)。
 *  3. 折叠多余空白为单个空格,首尾去空格。
 *  4. 转小写。
 * 例:`L. Messi`→`l messi`、`O. Dembélé`→`o dembele`、`Kylian Mbappé`→`kylian mbappe`、
 *    `Hakan Çalhanoğlu`→`hakan calhanoglu`、`Arda Güler`→`arda guler`。
 *
 * ⚠️ 部分字符 NFD 不会拆出 ASCII 基字母(它们本身就是独立码位,无组合记号):
 *    ø(O-stroke)、ı(无点 i)、ł(L-stroke)等。为保证 `Ødegaard`/`Yıldız`/`Lewandowski` 之类能命中,
 *    在归一化里额外做一次 ASCII 折叠映射(见 ASCII_FOLD)。
 *
 * 每个中文条目尽量挂多种 key:
 *  - 完整归一名(`kylian mbappe`)
 *  - 「首字母 + 姓」形(`l messi`、`o dembele`)——对齐 topscorers 的缩写形态
 *  - 姓氏唯一且常见时加姓氏兜底(`messi`、`haaland`)——但巴西/葡语单名/带 Júnior 者不可用 Júnior 当姓,
 *    用其真正的识别名(`vinicius`、`cunha`)兜底。
 *
 * 查不到返回 null,调用方应回退展示原始英文名。
 */

/** ø/ı/ł 等「独立码位变体」→ ASCII 折叠(NFD 不会处理这些)。 */
const ASCII_FOLD: Record<string, string> = {
  ø: 'o',
  Ø: 'o',
  ı: 'i',
  İ: 'i',
  ł: 'l',
  Ł: 'l',
  ð: 'd',
  Ð: 'd',
  þ: 'th',
  Þ: 'th',
  æ: 'ae',
  Æ: 'ae',
  œ: 'oe',
  Œ: 'oe',
  ß: 'ss',
};

/** 把原始球员名归一化为字典 key。详见文件头注释。 */
export function normalizeName(raw: string): string {
  return raw
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '') // 去组合用变音符
    .replace(/[øØıİłŁðÐþÞæÆœŒß]/g, (ch) => ASCII_FOLD[ch] ?? ch) // 折叠独立码位变体
    .replace(/\./g, '') // 去缩写点
    .replace(/-/g, ' ') // 连字符视作空格(Heung-min → heung min)
    .replace(/\s+/g, ' ') // 折叠空白
    .trim()
    .toLowerCase();
}

/**
 * 归一名 → 中文译名。
 * 同一球员可有多个 key(全名 / 缩写 / 姓氏兜底)都指向同一中文。
 */
export const PLAYER_ZH: Record<string, string> = {
  // ===== 当前真实射手/助攻榜(必须全覆盖) =====
  'l messi': '梅西',
  'lionel messi': '梅西',
  messi: '梅西',

  // 2026-07-02 助攻榜漏译补齐(用户报卡上出现英文名):榜单给的是缩写名,FULL 只有全名键 → 补短键。
  // 全名键已在 PLAYER_ZH_FULL(brahim diaz/roberto alvarado),此处不重复(两字典 key 互斥不变量)。
  'r alvarado': '阿尔瓦拉多', // Roberto Alvarado · 墨西哥
  'b diaz': '布拉欣·迪亚斯', // Brahim Díaz · 摩洛哥
  'b embolo': '恩博洛', // Breel Embolo · 瑞士
  'breel embolo': '恩博洛',

  'kylian mbappe': '姆巴佩',
  'k mbappe': '姆巴佩',
  mbappe: '姆巴佩',

  'o dembele': '登贝莱',
  'ousmane dembele': '登贝莱',
  dembele: '登贝莱',

  'vinicius junior': '维尼修斯',
  'vinicius jr': '维尼修斯',
  'vini jr': '维尼修斯',
  vinicius: '维尼修斯', // 单名兜底用识别名,不用 Júnior

  'e haaland': '哈兰德',
  'erling haaland': '哈兰德',
  haaland: '哈兰德',

  'd undav': '翁达夫',
  'deniz undav': '翁达夫',
  undav: '翁达夫',

  'j manzambi': '曼赞比',
  'johan manzambi': '曼赞比',
  manzambi: '曼赞比',

  'i sarr': '萨尔', // Ismaïla Sarr(塞内加尔);与 Pape Sarr 区分,故不给纯姓氏兜底
  'ismaila sarr': '萨尔',

  'b brobbey': '布罗贝',
  'brian brobbey': '布罗贝',
  brobbey: '布罗贝',

  'matheus cunha': '马特乌斯·库尼亚',
  'm cunha': '马特乌斯·库尼亚',
  cunha: '马特乌斯·库尼亚',

  'j david': '戴维',
  'jonathan david': '戴维',

  'i saibari': '赛巴里',
  'ismael saibari': '赛巴里',
  saibari: '赛巴里',

  'c summerville': '萨默维尔',
  'crysencio summerville': '萨默维尔',
  summerville: '萨默维尔',

  'p gueye': '帕佩·盖耶', // Pape Gueye(塞内加尔);Gueye 姓不唯一,见下方多人,故不给纯姓兜底
  'pape gueye': '帕佩·盖耶',

  'r vargas': '巴尔加斯',
  'ruben vargas': '巴尔加斯',

  'a ueda': '上田绮世',
  'ayase ueda': '上田绮世',
  ueda: '上田绮世',

  'c gakpo': '加克波',
  'cody gakpo': '加克波',
  gakpo: '加克波',

  'mikel oyarzabal': '奥亚萨瓦尔',
  'm oyarzabal': '奥亚萨瓦尔',
  oyarzabal: '奥亚萨瓦尔',

  'm araujo': '阿劳霍', // Manuel Araújo(乌拉圭)
  'manuel araujo': '阿劳霍',

  'a elanga': '埃兰加',
  'anthony elanga': '埃兰加',
  elanga: '埃兰加',

  'a isak': '伊萨克',
  'alexander isak': '伊萨克',
  isak: '伊萨克',

  'k de bruyne': '德布劳内',
  'kevin de bruyne': '德布劳内',
  'de bruyne': '德布劳内',

  'm olise': '奥利塞',
  'michael olise': '奥利塞',
  olise: '奥利塞',

  'b guimaraes': '布鲁诺·吉马良斯',
  'bruno guimaraes': '布鲁诺·吉马良斯',
  guimaraes: '布鲁诺·吉马良斯',

  'v gyokeres': '约克雷斯',
  'viktor gyokeres': '约克雷斯',
  gyokeres: '约克雷斯',

  'i ndiaye': '恩迪亚耶', // Iliman Ndiaye
  'iliman ndiaye': '恩迪亚耶',

  'n saliba': '萨利巴', // William Saliba 通译;此处按榜单缩写 N. 兜底
  'w saliba': '萨利巴',
  'william saliba': '萨利巴',
  saliba: '萨利巴',

  'f wirtz': '维尔茨',
  'florian wirtz': '维尔茨',
  wirtz: '维尔茨',

  pedri: '佩德里', // 单名
  'p gonzalez': '佩德里', // Pedri 本名 Pedro González,谨慎兜底

  'r lewandowski': '莱万多夫斯基',
  'robert lewandowski': '莱万多夫斯基',
  lewandowski: '莱万多夫斯基',

  'm odegaard': '厄德高',
  'martin odegaard': '厄德高',
  odegaard: '厄德高',

  'arda guler': '阿尔达·居莱尔',
  'a guler': '阿尔达·居莱尔',
  guler: '阿尔达·居莱尔',

  'hakan calhanoglu': '恰尔汗奥卢',
  'h calhanoglu': '恰尔汗奥卢',
  calhanoglu: '恰尔汗奥卢',

  'kenan yildiz': '耶尔德兹',
  'k yildiz': '耶尔德兹',
  yildiz: '耶尔德兹',

  'idrissa gana gueye': '加纳·盖耶', // Idrissa Gana Gueye(塞内加尔中场)
  'idrissa gueye': '加纳·盖耶',
  'gana gueye': '加纳·盖耶',
  'i gueye': '加纳·盖耶',

  // ===== 扩充:国际大赛级常见球星(各强队核心) =====

  // —— 阿根廷 ——
  'l martinez': '劳塔罗·马丁内斯', // Lautaro Martínez
  'lautaro martinez': '劳塔罗·马丁内斯',
  lautaro: '劳塔罗·马丁内斯',
  'a di maria': '迪马利亚',
  'angel di maria': '迪马利亚',
  'di maria': '迪马利亚',
  'j alvarez': '阿尔瓦雷斯', // Julián Álvarez
  'julian alvarez': '阿尔瓦雷斯',
  'e martinez': '埃米利亚诺·马丁内斯', // Emiliano Martínez(门将,“迪布”)
  'emiliano martinez': '埃米利亚诺·马丁内斯',
  'r de paul': '德保罗',
  'rodrigo de paul': '德保罗',
  'de paul': '德保罗',
  'e fernandez': '恩佐·费尔南德斯', // Enzo Fernández
  'enzo fernandez': '恩佐·费尔南德斯',
  enzo: '恩佐·费尔南德斯',
  'a mac allister': '麦卡利斯特',
  'alexis mac allister': '麦卡利斯特',
  'mac allister': '麦卡利斯特',
  'n otamendi': '奥塔门迪',
  otamendi: '奥塔门迪',

  // —— 巴西 ——
  neymar: '内马尔',
  'neymar jr': '内马尔',
  'r jesus': '热苏斯', // Gabriel Jesus
  'gabriel jesus': '热苏斯',
  jesus: '热苏斯',
  rodrygo: '罗德里戈', // 单名
  raphinha: '拉菲尼亚', // 单名
  richarlison: '里沙利松', // 单名
  casemiro: '卡塞米罗', // 单名
  'casimiro': '卡塞米罗',
  marquinhos: '马尔基尼奥斯', // 单名
  militao: '米利唐', // Éder Militão
  'e militao': '米利唐',
  'g jesus': '热苏斯',
  'a paqueta': '帕奎塔',
  'lucas paqueta': '帕奎塔',
  paqueta: '帕奎塔',
  'rodrygo goes': '罗德里戈',

  // —— 法国 ——
  'a griezmann': '格列兹曼',
  'antoine griezmann': '格列兹曼',
  griezmann: '格列兹曼',
  'a tchouameni': '楚阿梅尼',
  'aurelien tchouameni': '楚阿梅尼',
  tchouameni: '楚阿梅尼',
  'e camavinga': '卡马文加',
  'eduardo camavinga': '卡马文加',
  camavinga: '卡马文加',
  'w saliba fr': '萨利巴', // 占位避免与上方冲突(实际同 saliba)
  'i konate': '科纳特',
  'ibrahima konate': '科纳特',
  konate: '科纳特',
  'm thuram': '马库斯·图拉姆', // Marcus Thuram
  'marcus thuram': '马库斯·图拉姆',
  thuram: '马库斯·图拉姆',
  'b barcola': '巴尔科拉',
  'bradley barcola': '巴尔科拉',
  barcola: '巴尔科拉',
  'r kolo muani': '科洛·穆阿尼',
  'randal kolo muani': '科洛·穆阿尼',
  'kolo muani': '科洛·穆阿尼',
  'k coman': '科曼', // Kingsley Coman
  'kingsley coman': '科曼',
  coman: '科曼',
  'u kone': '科内',
  maignan: '迈尼昂',
  'm maignan': '迈尼昂',

  // —— 英格兰 ——
  'h kane': '凯恩',
  'harry kane': '凯恩',
  kane: '凯恩',
  'j bellingham': '贝林厄姆',
  'jude bellingham': '贝林厄姆',
  bellingham: '贝林厄姆',
  'p foden': '福登',
  'phil foden': '福登',
  foden: '福登',
  'b saka': '萨卡',
  'bukayo saka': '萨卡',
  saka: '萨卡',
  'c palmer': '帕尔默',
  'cole palmer': '帕尔默',
  palmer: '帕尔默',
  'd rice': '赖斯',
  'declan rice': '赖斯',
  rice: '赖斯',
  'm rashford': '拉什福德',
  'marcus rashford': '拉什福德',
  rashford: '拉什福德',
  'j grealish': '格拉利什',
  grealish: '格拉利什',
  'h maguire': '马奎尔',
  maguire: '马奎尔',
  'j pickford': '皮克福德',
  pickford: '皮克福德',
  'a gordon': '戈登', // Anthony Gordon
  'trent alexander arnold': '阿诺德',
  'alexander arnold': '阿诺德',
  'j stones': '斯通斯',
  stones: '斯通斯',

  // —— 西班牙 ——
  'l yamal': '亚马尔',
  'lamine yamal': '亚马尔',
  yamal: '亚马尔',
  'n williams': '尼科·威廉姆斯', // Nico Williams
  'nico williams': '尼科·威廉姆斯',
  'd olmo': '奥尔莫',
  'dani olmo': '奥尔莫',
  olmo: '奥尔莫',
  'r rodri': '罗德里', // Rodri(Rodrigo Hernández)单名
  rodri: '罗德里',
  'a morata': '莫拉塔',
  'alvaro morata': '莫拉塔',
  morata: '莫拉塔',
  'f torres': '费兰·托雷斯', // Ferran Torres
  'ferran torres': '费兰·托雷斯',
  'unai simon': '乌奈·西蒙',
  'r le normand': '勒诺尔曼',
  'le normand': '勒诺尔曼',
  'm merino': '梅里诺',
  'mikel merino': '梅里诺',
  merino: '梅里诺',
  'f ruiz': '法比安·鲁伊斯',
  'fabian ruiz': '法比安·鲁伊斯',

  // —— 葡萄牙 ——
  'cristiano ronaldo': 'C罗',
  'c ronaldo': 'C罗',
  ronaldo: 'C罗', // 葡语该赛事语境下默认 C 罗
  'b fernandes': 'B费', // Bruno Fernandes
  'bruno fernandes': 'B费',
  'b silva': '贝尔纳多·席尔瓦', // Bernardo Silva
  'bernardo silva': '贝尔纳多·席尔瓦',
  'r leao': '莱昂',
  'rafael leao': '莱昂',
  leao: '莱昂',
  'j felix': '若昂·费利克斯',
  'joao felix': '若昂·费利克斯',
  felix: '若昂·费利克斯',
  'v dias': '鲁本·迪亚斯', // Rúben Dias
  'ruben dias': '鲁本·迪亚斯',
  'd nunez': '努涅斯', // Darwin Núñez(乌拉圭,但常见)
  'darwin nunez': '努涅斯',
  nunez: '努涅斯',
  vitinha: '维蒂尼亚', // 单名
  'p neto': '佩德罗·内托',
  'pedro neto': '佩德罗·内托',
  'g ramos': '贡萨洛·拉莫斯',
  'goncalo ramos': '贡萨洛·拉莫斯',

  // —— 德国 ——
  'j musiala': '穆西亚拉',
  'jamal musiala': '穆西亚拉',
  musiala: '穆西亚拉',
  'k havertz': '哈弗茨',
  'kai havertz': '哈弗茨',
  havertz: '哈弗茨',
  'i gundogan': '京多安',
  'ilkay gundogan': '京多安',
  gundogan: '京多安',
  'a rudiger': '吕迪格',
  'antonio rudiger': '吕迪格',
  rudiger: '吕迪格',
  'j kimmich': '基米希',
  'joshua kimmich': '基米希',
  kimmich: '基米希',
  'l sane': '萨内',
  'leroy sane': '萨内',
  sane: '萨内',
  'n schlotterbeck': '施洛特贝克',
  'm neuer': '诺伊尔',
  neuer: '诺伊尔',
  'serge gnabry': '格纳布里',
  gnabry: '格纳布里',

  // —— 荷兰 ——
  'v van dijk': '范迪克',
  'virgil van dijk': '范迪克',
  'van dijk': '范迪克',
  'f de jong': '弗兰基·德容', // Frenkie de Jong
  'frenkie de jong': '弗兰基·德容',
  'de jong': '弗兰基·德容',
  'm depay': '德佩',
  'memphis depay': '德佩',
  depay: '德佩',
  'd dumfries': '邓弗里斯',
  dumfries: '邓弗里斯',
  'x simons': '西蒙斯', // Xavi Simons
  'xavi simons': '西蒙斯',

  // —— 比利时 ——
  'r lukaku': '卢卡库',
  'romelu lukaku': '卢卡库',
  lukaku: '卢卡库',
  'j doku': '多库',
  'jeremy doku': '多库',
  doku: '多库',
  'l openda': '奥彭达',
  'loic openda': '奥彭达',
  openda: '奥彭达',

  // —— 克罗地亚 ——
  'l modric': '莫德里奇',
  'luka modric': '莫德里奇',
  modric: '莫德里奇',
  'a kramaric': '克拉马里奇',
  kramaric: '克拉马里奇',

  // —— 韩国 / 日本 ——
  'son heung min': '孙兴慜',
  'h son': '孙兴慜',
  'heung min son': '孙兴慜',
  'k kubo': '久保建英',
  'takefusa kubo': '久保建英',
  kubo: '久保建英',
  'k mitoma': '三笘薫',
  'kaoru mitoma': '三笘薫',
  mitoma: '三笘薫',
  'd kamada': '镰田大地',
  'daichi kamada': '镰田大地',
  kamada: '镰田大地',
  'w endo': '远藤航',
  'wataru endo': '远藤航',
  'r doan': '堂安律',
  'ritsu doan': '堂安律',
  doan: '堂安律',

  // —— 厄瓜多尔 / 其它南美 ——
  'm caicedo': '凯塞多', // Moisés Caicedo
  'moises caicedo': '凯塞多',
  caicedo: '凯塞多',
  'e valencia': '埃内尔·瓦伦西亚',
  'enner valencia': '埃内尔·瓦伦西亚',
  'l suarez': '苏亚雷斯', // Luis Suárez(乌拉圭)
  'luis suarez': '苏亚雷斯',
  'f valverde': '巴尔韦德',
  'federico valverde': '巴尔韦德',
  valverde: '巴尔韦德',
  'j gimenez': '希门尼斯', // José Giménez
  'jose gimenez': '希门尼斯',

  // —— 非洲核心 ——
  'm salah': '萨拉赫',
  'mohamed salah': '萨拉赫',
  salah: '萨拉赫',
  'v osimhen': '奥斯梅恩',
  'victor osimhen': '奥斯梅恩',
  osimhen: '奥斯梅恩',
  'a hakimi': '阿什拉夫·哈基米',
  'achraf hakimi': '阿什拉夫·哈基米',
  hakimi: '阿什拉夫·哈基米',
  'h ziyech': '齐耶赫',
  'hakim ziyech': '齐耶赫',
  ziyech: '齐耶赫',
  'sadio mane': '马内',
  's mane': '马内',
  mane: '马内',
  'a traore': '阿达马·特拉奥雷',
  'andre onana': '奥纳纳',
  onana: '奥纳纳',
  'serhou guirassy': '吉拉西',
  guirassy: '吉拉西',

  // —— 北欧 / 其它欧洲 ——
  'd vlahovic': '弗拉霍维奇',
  'dusan vlahovic': '弗拉霍维奇',
  vlahovic: '弗拉霍维奇',
  'k schmeichel': '小舒梅切尔',
  'c eriksen': '埃里克森',
  'christian eriksen': '埃里克森',
  eriksen: '埃里克森',
  'r hojlund': '霍伊伦',
  'rasmus hojlund': '霍伊伦',
  hojlund: '霍伊伦',
  'd zakharyan': '扎哈良',
  'g xhaka': '扎卡',
  'granit xhaka': '扎卡',
  xhaka: '扎卡',
  'm akanji': '阿坎吉',
  'manuel akanji': '阿坎吉',
  akanji: '阿坎吉',
  'h mkhitaryan': '姆希塔良',
  'henrikh mkhitaryan': '姆希塔良',
  mkhitaryan: '姆希塔良',

  // —— 美国 / 加拿大 ——
  'c pulisic': '普利西奇',
  'christian pulisic': '普利西奇',
  pulisic: '普利西奇',
  'w mckennie': '麦肯尼',
  mckennie: '麦肯尼',
  'a davies': '阿方索·戴维斯', // Alphonso Davies(加拿大,与 Jonathan David 区分)
  'alphonso davies': '阿方索·戴维斯',
  davies: '阿方索·戴维斯',
};

/**
 * 查英文(任意形态)球员名的中文译名。
 * @param raw API-Football 返回的原始名(缩写 / 全名 / 带变音符均可)
 * @returns 命中返回中文译名,未命中返回 null(调用方回退展示原始英文)
 */
// 全员中文译名(477 名·覆盖各队首发/替补 Top5·批量音译·6/27)。仅作 lookupPlayerZh 兜底,
// 上方 PLAYER_ZH(精校知名球星)优先,故 Güler→居莱尔 等不被此处覆盖。
export const PLAYER_ZH_FULL: Record<string, string> = {
  'aaron wan bissaka': '万-比萨卡',
  'abbosbek fayzullaev': '法伊祖拉耶夫',
  'abdallah nasib': '纳西卜',
  'abdulelah al amri': '阿姆里',
  'abdulkerim bardakci': '巴尔达克奇',
  'abdulla abdullaev': '阿卜杜拉耶夫',
  'abdullah al khaibari': '海巴里',
  'abduvokhid nematov': '内马托夫',
  'adam hlozek': '赫洛热克',
  'adrien rabiot': '拉比奥',
  'agustin canobbio': '卡诺比奥',
  'ahmed basil': '巴西尔',
  'ahmed fathi': '法蒂',
  'ahmed nadhir benbouali': '本布阿利',
  'aiden o\'neill': '奥尼尔',
  'aissa mandi': '曼迪',
  'akam hashem': '哈希姆',
  'akram afif': '阿菲夫',
  'ala\'a al hejji': '海吉',
  'alan franco': '弗兰科',
  'alessandro circati': '西尔卡蒂',
  'alex baena': '巴埃纳',
  'alexander freeman': '弗里曼',
  'alexandr sojka': '索伊卡',
  'ali abdi': '阿卜迪',
  'ali ahmed': '艾哈迈德',
  'ali al hamadi': '哈马迪',
  'ali jasim': '贾西姆',
  'ali lajami': '拉贾米',
  'ali nemati': '内马蒂',
  'ali olwan': '奥尔万',
  'ali yousif': '优素福',
  'alireza beiranvand': '贝兰万德',
  alisson: '阿利松',
  'alistair johnston': '约翰斯顿',
  'alvaro fidalgo': '菲达尔戈',
  'amad diallo': '迪亚洛',
  'amine ben hmida': '本希达',
  'amine gouiri': '古伊里',
  'amir al ammari': '阿马里',
  'amir hadziahmetovic': '哈季亚赫梅托维奇',
  'amir murillo': '穆里略',
  'andreas schjelderup': '舍尔德鲁普',
  'andres andrade': '安德拉德',
  'andres cubas': '库巴斯',
  'andres gomez': '戈麦斯',
  'andy robertson': '罗伯逊',
  'angus gunn': '冈恩',
  'anis ben slimane': '本斯利曼',
  'ante budimir': '布迪米尔',
  'antonee robinson': '罗宾逊',
  'antonio sanabria': '萨纳夫里亚',
  'ao tanaka': '田中碧',
  'aria yousefi': '优素菲',
  'armando obispo': '奥比斯波',
  'arthur masuaku': '马苏阿库',
  'aubrey modiba': '莫迪巴',
  'auston trusty': '特拉斯蒂',
  'aymen dahmen': '达赫曼',
  'aymen hussein': '侯赛因',
  'aymeric laporte': '拉波尔特',
  'azizjon ganiev': '加尼耶夫',
  'baris alper yilmaz': '耶尔马兹',
  'bart verbruggen': '维尔布鲁根',
  'bekhruz karimov': '卡里莫夫',
  'ben gannon doak': '多克',
  'benjamin asare': '阿萨雷',
  'besfort zeneli': '泽内利',
  'bilal el khannouss': '哈努斯',
  bono: '博诺',
  'boualem khoukhi': '胡基',
  'brahim diaz': '布拉欣·迪亚斯',
  'brandon mechele': '梅赫勒',
  'brian gutierrez': '古铁雷斯',
  'caleb yirenkyi': '伊伦基',
  'callan elliot': '埃利奥特',
  'cedric bakambu': '巴坎布',
  'chadi riad': '里亚德',
  'chris richards': '理查兹',
  'christ inao oulai': '乌莱',
  'connor metcalfe': '梅特卡夫',
  'cristian romero': '罗梅罗',
  'cristian volpato': '沃尔帕托',
  'cyle larin': '拉林',
  'daizen maeda': '前田大然',
  'daniel munoz': '穆尼奥斯',
  'danley jean jacques': '让·雅克',
  'david alaba': '阿拉巴',
  'david doudera': '杜代拉',
  'david moller wolfe': '沃尔夫',
  'davinson sanchez': '桑切斯',
  'dayot upamecano': '乌帕梅卡诺',
  'dennis hadzikadunic': '哈季卡杜尼奇',
  'denzel dumfries': '邓弗里斯',
  'deroy duarte': '杜阿尔特',
  'desire doue': '杜埃',
  'diney borges': '迪内伊',
  'djed spence': '斯彭斯',
  'dominik livakovic': '利瓦科维奇',
  'dominique simon': '西蒙',
  'dostonbek khamdamov': '哈姆达莫夫',
  'douglas santos': '道格拉斯·桑托斯',
  'edin dzeko': '哲科',
  'edmilson junior': '埃德米尔森',
  'edouard mendy': '门迪',
  'edson alvarez': '阿尔瓦雷斯',
  'egil selvik': '塞尔维克',
  'eldor shomurodov': '绍穆罗多夫',
  'elijah just': '贾斯特',
  'ellyes skhiri': '斯希里',
  'eloy room': '鲁姆',
  'emam ashour': '阿舒尔',
  'emmanuel agbadou': '阿格巴杜',
  'eren elmali': '埃尔马勒',
  'erik lira': '利拉',
  'ermedin demirovic': '德米罗维奇',
  'ermin mahmic': '马赫米奇',
  'evidence makgopa': '马克戈帕',
  'ezri konsa': '孔萨',
  'felix nmecha': '恩梅查',
  'finn surman': '瑟曼',
  'folarin balogun': '巴洛贡',
  'franck kessie': '凯西',
  'gabriel gudmundsson': '古德蒙松',
  'gabriel magalhaes': '加布里埃尔',
  'gabriel martinelli': '马丁内利',
  martinelli: '马丁内利', // 姓氏唯一,兜底
  'gessime yassine': '亚辛',
  'gi hyuk lee': '李基赫',
  'gideon mensah': '门萨',
  'giovanni reyna': '雷纳',
  'grant hanley': '汉利',
  'gregor kobel': '科贝尔',
  'guela doue': '盖拉·杜埃',
  'gustavo gomez': '古斯塔沃·戈麦斯',
  'gustavo puerta': '普埃尔塔',
  'gustavo velazquez': '贝拉斯克斯',
  'hamdy fathy': '法蒂',
  'haissem hassan': '哈桑',
  'hannibal mejbri': '梅杰布里',
  'harry souttar': '索塔尔',
  'hassan al haydos': '海多斯',
  'hazem mastouri': '马斯图里',
  'helio varela': '瓦雷拉',
  'hernan galindez': '加林德斯',
  'homam al amin': '阿明',
  'hossein kanaani': '卡纳尼',
  'houssem aouar': '奥瓦尔',
  'husam ali mohammad abudahab': '阿布达哈卜',
  'hwang in beom': '黄仁范',
  'hyeon gyu oh': '吴贤揆',
  'ibrahim bayesh': '巴耶什',
  'ibrahim mbaye': '姆巴耶',
  'ibrahim sangare': '桑加雷',
  'igor sergeev': '谢尔盖耶夫',
  'ime okon': '奥孔',
  'isak hien': '希恩',
  'ismael gharbi': '加尔比',
  'ismail yuksek': '于克塞克',
  'israel reyes': '雷耶斯',
  'issa laye': '拉耶',
  'ivan basic': '巴希奇',
  'ivan sunjic': '顺伊奇',
  'jack hendry': '亨德里',
  'jackson irvine': '厄温',
  'jacob widell zetterstrom': '泽特斯特伦',
  'jalal hassan': '哈桑',
  'jaminton campaz': '坎帕斯',
  'jacob shaffelburg': '沙夫尔堡',
  'jan paul van hecke': '范赫克',
  'jaroslav zeleny': '泽莱尼',
  'jason geria': '杰里亚',
  'jayden adams': '亚当斯',
  'jean kevin duverne': '杜韦尔内',
  'jean ricner bellegarde': '贝勒加德',
  'jefferson lerma': '莱尔马',
  'jeremy antonisse': '安东尼斯',
  'jerome opoku': '奥波库',
  'jesse randall': '兰德尔',
  'jhon arias': '阿里亚斯',
  'jhon lucumi': '卢库米',
  'ji sung eom': '严志成',
  'jin gyu kim': '金珍圭',
  'jiovany ramos': '拉莫斯',
  'joao neves': '内维斯',
  'joao paulo': '若昂·保罗',
  'joel ordonez': '奥尔多涅斯',
  'johan mojica': '莫希卡',
  'johan vasquez': '巴斯克斯',
  'johny placide': '普拉西德',
  'jonas adjei adjetey': '阿杰泰',
  'jonathan tah': '塔',
  'jordan ayew': '阿尤',
  'jordan bos': '博斯',
  'jorge sanchez': '豪尔赫·桑切斯',
  'joris kayembe': '卡延贝',
  'jose fajardo': '法哈多',
  'joshua brenet': '布雷内',
  'josip stanisic': '斯塔尼希奇',
  'josip sutalo': '舒塔洛',
  'jovo lukic': '卢基奇',
  'juan caceres': '卡塞雷斯',
  'juan fernando quintero': '金特罗',
  'juan sanabria': '胡安·萨纳夫里亚',
  'jules kounde': '孔德',
  'julian quinones': '基尼奥内斯',
  'julian ryerson': '里尔森',
  'julio enciso': '恩西索',
  'juninho bacuna': '巴库纳',
  'jurgen locadia': '洛卡迪亚',
  'jurien gaari': '加里',
  'kaan ayhan': '艾汉',
  'kaishu sano': '佐野海舟',
  'kang in lee': '李刚仁',
  'karim boudiaf': '布迪亚夫',
  'karim hafez': '哈菲兹',
  'keito nakamura': '中村敬斗',
  'kerim alajbegovic': '阿拉伊贝戈维奇',
  'kevin danso': '丹索',
  'kevin lenini': '莱尼尼',
  'kevin rodriguez': '罗德里格斯',
  'khalid al ghannam': '甘纳姆',
  'khuliso mudau': '穆道',
  'kieran tierney': '蒂尔尼',
  'kim min jae': '金玟哉',
  'kim seung gyu': '金承奎',
  'ko itakura': '板仓滉',
  'krepin diatta': '迪亚塔',
  'kristian thorstvedt': '托尔斯特韦特',
  'kristoffer ajer': '阿耶尔',
  'ladislav krejci': '克雷伊奇',
  'lamine camara': '卡马拉',
  'laros duarte': '拉罗斯·杜阿尔特',
  'lawrence ati zigi': '齐吉',
  'leandro bacuna': '莱安德罗·巴库纳',
  'leandro trossard': '特罗萨德',
  'lee tae seok': '李泰锡',
  'lenny joseph': '约瑟夫',
  'leo ostigard': '厄斯蒂高',
  'lewis ferguson': '弗格森',
  'lionel mpasi nzau': '姆帕西',
  'lisandro martinez': '利桑德罗·马丁内斯',
  'livano comenencia': '科梅嫩西亚',
  'luca zidane': '卢卡·齐达内',
  'lucas herrington': '赫林顿',
  'luis diaz': '路易斯·迪亚斯',
  'luis romo': '罗莫',
  'luiz henrique': '路易斯·恩里克',
  'lukas cerv': '切尔夫',
  'lukas provod': '普罗沃德',
  'mahmoud al mardi': '马尔迪',
  'mahmoud saber': '萨贝尔',
  'mahmoud trezeguet': '特雷泽盖',
  'malik tillman': '蒂尔曼',
  'marc guehi': '盖伊',
  'marcel sabitzer': '扎比策尔',
  'marcos llorente': '略伦特',
  'marcus pedersen': '佩德森',
  'mario pasalic': '帕萨利奇',
  'marko arnautovic': '阿尔瑙托维奇',
  'marko farji': '法尔吉',
  'marko stamenic': '斯塔梅尼奇',
  'martin baturina': '巴图里纳',
  'martin experience': '埃克斯佩里昂斯',
  'marvin senaya': '塞纳亚',
  'marwan attia': '阿提亚',
  'matej kovar': '科瓦日',
  'mateo chavez': '查韦斯',
  'mateo kovacic': '科瓦契奇',
  'mathias olivera': '奥利韦拉',
  'mathieu choiniere': '舒瓦尼耶',
  'matias galarza': '加拉萨',
  'mattias svanberg': '斯万贝里',
  mauricio: '毛里西奥',
  'max crocombe': '克罗科姆',
  'maxim de cuyper': '德库珀',
  'maxime crepeau': '克雷波',
  'maximiliano araujo': '阿劳霍',
  'mbekezeli mbokazi': '姆博卡齐',
  'mehdi taremi': '塔雷米',
  'merchas doski': '多斯基',
  'michael boxall': '博克萨尔',
  'michal sadilek': '萨迪莱克',
  'michel aebischer': '埃比舍尔',
  'mike maignan': '迈尼昂',
  'milad mohammadi': '穆罕默迪',
  'miles robinson': '迈尔斯·罗宾逊',
  'mohamed belhadj mahmoud': '贝勒哈吉',
  'mohamed hany': '哈尼',
  'mohamed kanno': '坎诺',
  'mohammad ali hasheesh': '哈希什',
  'mohammad mohebi': '莫赫比',
  'mohammed abu al shamat': '沙马特',
  'mohammed al owais': '奥韦斯',
  'mohanad lasheen': '拉欣',
  'mohannad abu taha': '阿布塔哈',
  'montassar talbi': '塔尔比',
  'morgan rogers': '罗杰斯',
  'mostafa shobeir': '绍贝尔',
  'mostafa ziko': '齐科',
  'moteb al harbi': '哈尔比',
  'mousa tamari': '塔马里',
  'moussa niakhate': '尼亚卡特',
  'nabil bentaleb': '本塔莱布',
  'nathan dylan saliba': '萨利巴',
  'nathan ngoy': '恩戈伊',
  'nathaniel brown': '布朗',
  'neil el aynaoui': '埃纳维',
  'nestory irankunda': '伊兰昆达',
  'ngal\'ayel mukau': '穆考',
  'nico schlotterbeck': '施洛特贝克',
  'nicolas de la cruz': '德拉克鲁斯',
  'nicolas pepe': '佩佩',
  'nicolas raskin': '拉斯金',
  'nicolas seiwald': '塞瓦尔德',
  'niko sigur': '西居尔',
  'nikola katic': '卡蒂奇',
  'nilson angulo': '安古洛',
  'noah sadiki': '萨迪基',
  'noni madueke': '马杜埃凯',
  'noussair mazraoui': '马兹拉维',
  'nuno mendes': '努诺·门德斯',
  'odeh fakhoury': '法胡里',
  'omar alderete': '阿尔德雷特',
  'omar marmoush': '马尔穆什',
  'omar rekik': '雷基克',
  'orlando gill': '吉尔',
  'orlando mosquera': '莫斯克拉',
  'oscar bobb': '博布',
  'oswin appollis': '阿波利斯',
  'otabek shukurov': '舒库罗夫',
  'pathe ismael ciss': '锡斯',
  'patrick beach': '比奇',
  'patrick berg': '贝里',
  'pau cubarsi': '库巴西',
  'paul okon engstler': '奥孔-恩格斯特勒',
  'pedro miguel': '佩德罗·米格尔',
  'pedro vite': '维特',
  'petar musa': '穆萨',
  'philipp lienhart': '利恩哈特',
  pico: '皮科',
  'piero hincapie': '因卡皮耶',
  'promise david': '戴维',
  'ramin rezaeian': '雷扎伊安',
  'ramon sosa': '索萨',
  'ramy bensebaini': '本塞拜尼',
  'raul jimenez': '希门尼斯',
  'raul rangel': '兰赫尔',
  rayan: '拉扬',
  'reece james': '里斯·詹姆斯',
  'remo freuler': '弗罗伊勒',
  'renato veiga': '维加',
  'ricardo ade': '阿德',
  'ricardo rodriguez': '里卡多·罗德里格斯',
  'richie laryea': '拉里亚',
  'riyad mahrez': '马赫雷斯',
  'roberto alvarado': '阿尔瓦拉多',
  'rodrigo bentancur': '本坦库尔',
  'romano schmid': '施密德',
  'ronwen williams': '威廉姆斯',
  'ruben providence': '普罗维登斯',
  'ryan christie': '克里斯蒂',
  'ryan gravenberch': '格拉文贝赫',
  'ryan mendes': '瑞安·门德斯',
  'ryan thomas': '托马斯',
  'saeid ezatolahi': '埃扎托拉希',
  'saleh hardani': '哈尔达尼',
  'salem al dawsari': '多萨里',
  'salih ozcan': '厄兹詹',
  'sander berge': '贝尔格',
  berge: '贝尔格', // 与 patrick berg(贝里)不同拼写,归一化后不撞
  'sarpreet singh': '辛格',
  'saud abdulhamid': '阿卜杜勒哈米德',
  'sead kolasinac': '科拉希纳茨',
  'sebastian berhalter': '贝哈尔特',
  'shahriar moghanlou': '莫甘卢',
  'sherel constancio floranus': '弗洛拉努斯',
  'shoja khalilzadeh': '哈利勒扎德',
  'sidny lopes cabral': '卡布拉尔',
  'sontje hansen': '汉森',
  'soufiane rahimi': '拉希米',
  'stephen eustaquio': '厄斯塔基奥',
  'stjepan radeljic': '拉代利奇',
  'sultan al brake': '布拉克',
  'sultan mandash': '曼达什',
  'taha abdi ali': '塔哈',
  'takehiro tomiyasu': '富安健洋',
  'tani oluwaseyi': '奥卢瓦塞伊',
  'tarik muharemovic': '穆哈雷莫维奇',
  'teboho mokoena': '莫科埃纳',
  'thapelo maseko': '马塞科',
  'thelo aasgaard': '奥斯戈',
  'thibaut courtois': '库尔图瓦',
  'thomas partey': '帕尔特伊',
  'tijjani reijnders': '赖因德斯',
  'tim ream': '里姆',
  'timothy castagne': '卡斯塔涅',
  'tony ralston': '拉尔斯顿',
  'tyler bindon': '宾登',
  'tyrese noslin': '诺斯林',
  'vladimir coufal': '库法尔',
  vozinha: '沃津哈',
  'weston mckennie': '麦肯尼',
  'wilfried singo': '辛戈',
  'willian pacho': '帕乔',
  'wilson isidor': '伊西多尔',
  'yahia fofana': '福法纳',
  'yan diomande': '迪奥曼德',
  'yan valery': '瓦莱里',
  'yasin ayari': '阿亚里',
  'yassine bounou': '布努',
  'yazeed abu laila': '阿布莱拉',
  'yoane wissa': '维萨',
  'yoel barcenas': '巴塞纳斯',
  'young woo seol': '薛荣佑',
  'youri tielemans': '蒂勒曼斯',
  'yukinari sugawara': '菅原由势',
  'yusuf abdurisag': '阿卜杜里萨格',
  'zeki celik': '切利克',
  'zidane iqbal': '伊克巴尔',
  'zion suzuki': '铃木彩艳',
  zizo: '齐佐',

  // ===== 2026-07-03 批量补译:32强淘汰赛全员(生产库 stats.players/events 全量 diff,864 键) =====
  'a abdi': '阿卜迪',
  'a afif': '阿菲夫',
  'a ahmed': '艾哈迈德',
  'a al ammari': '阿马里',
  'a al amri': '阿姆里',
  'a al ganehi': '加内希',
  'a al hamadi': '哈马迪',
  'a al hamdan': '哈姆丹',
  'a al hussain': '侯赛因',
  'a al khaibari': '海巴里',
  'a al oui': '奥维',
  'a al reeshawee': '里沙维',
  'a alaaeldin': '阿拉埃尔丁',
  'a ali': '阿里',
  'a alipour': '阿里普尔',
  'a amaimouni': '阿马伊穆尼',
  'a amonov': '阿莫诺夫',
  'a andrade': '安德拉德',
  'a arce': '阿尔塞',
  'a azaizeh': '阿扎伊泽',
  'a baena': '巴埃纳',
  'a bardakci': '巴尔达克奇',
  'a basil': '巴西尔',
  'a behich': '贝希奇',
  'a bernhardsson': '伯恩哈德松',
  'a bonny': '邦尼',
  'a bouaddi': '布阿迪',
  'a boulbina': '布尔比纳',
  'a budimir': '布迪米尔',
  'a canobbio': '卡诺比奥',
  'a cubas': '库巴斯',
  'a diallo': '迪亚洛',
  'a diao': '迪奥',
  'a el kaabi': '埃尔卡比',
  'a fathi': '法蒂',
  'a fatouh': '法图赫',
  'a fayzullaev': '法伊祖拉耶夫',
  'a fidalgo': '菲达尔戈',
  'a franco': '弗兰科',
  'a freeman': '弗里曼',
  'a ganiev': '加尼耶夫',
  'a gigovic': '吉戈维奇',
  'a godoy': '戈多伊',
  'a gomez': '戈麦斯',
  'a gonzalez': '冈萨雷斯',
  'a gouiri': '古伊里',
  'a hadj moussa': '哈吉穆萨',
  'a hadziahmetovic': '哈季亚赫梅托维奇',
  'a hatem': '哈特姆',
  'a hejji': '赫吉',
  'a hickey': '希基',
  'a hlozek': '赫洛热克',
  'a hosseinzadeh': '侯赛因扎德',
  'a hrustic': '赫鲁斯蒂奇',
  'a hussein': '侯赛因',
  'a jahanbakhsh': '贾汉巴赫什',
  'a jamous': '贾穆斯',
  'a jashari': '亚沙里',
  'a jasim': '贾西姆',
  'a khusanov': '胡萨诺夫',
  'a lajami': '拉贾米',
  'a laporte': '拉波尔特',
  'a londono': '隆多尼奥',
  'a maidana': '马伊达纳',
  'a malic': '马利奇',
  'a masuaku': '马苏阿库',
  'a memic': '梅米奇',
  'a minda': '明达',
  'a modiba': '莫迪巴',
  'a mozgovoy': '莫兹戈沃伊',
  'a nasib': '纳西卜',
  'a nemati': '内马蒂',
  'a nematov': '内马托夫',
  'a nusa': '努萨',
  'a o madibo': '马迪博',
  'a olwan': '奥尔万',
  'a onana': '奥纳纳',
  'a ounahi': '乌纳希',
  'a pavlovic': '帕夫洛维奇',
  'a prass': '普拉斯',
  'a preciado': '普雷西亚多',
  'a qasem': '卡塞姆',
  'a quintero': '金特罗',
  'a rabiot': '拉比奥',
  'a ralston': '拉尔斯顿',
  'a robertson': '罗伯逊',
  'a robinson': '罗宾逊',
  'a saelemaekers': '萨勒马克尔斯',
  'a salah eddine': '萨拉赫丁',
  'a sanabria': '萨纳夫里亚',
  'a schjelderup': '舍尔德鲁普',
  'a seck': '塞克',
  'a seko': '塞科',
  'a sher': '谢尔',
  'a slimane': '斯利马内',
  'a sojka': '索伊卡',
  'a sorloth': '索尔洛特',
  'a tanaka': '田中碧',
  'a theate': '特亚特',
  'a trusty': '特拉斯蒂',
  'a vega': '维加',
  'a wan bissaka': '万-比萨卡',
  'a yousefi': '优素菲',
  'a yousif': '优素福',
  'a zendejas': '曾德哈斯',
  'aaron hickey': '希基',
  'abdukodir khusanov': '胡萨诺夫',
  'abdul fatawu issahaku': '伊萨哈库',
  'ahmed fatouh': '法图赫',
  'akmal mozgovoy': '莫兹戈沃伊',
  'aleksandar pavlovic': '帕夫洛维奇',
  'alex arce': '阿尔塞',
  'alex sandro': '阿莱士·桑德罗',
  'ali al azaizeh': '阿扎伊泽',
  'amar dedic': '德迪奇',
  'ange yoan bonny': '邦尼',
  'angelo preciado': '普雷西亚多',
  'angelo stiller': '施蒂勒',
  'anthony gordon': '戈登',
  'armin gigovic': '吉戈维奇',
  'arthur theate': '特亚特',
  'assim madibo': '马迪博',
  'axel tuanzebe': '图安泽贝',
  'ayyoub bouaddi': '布阿迪',
  'azarias londono': '隆多尼奥',
  'azzedine ounahi': '乌纳希',
  'b aaronson': '阿伦森',
  'b asare': '阿萨雷',
  'b cipenga': '西彭加',
  'b dieng': '迪昂',
  'b el khannouss': '哈努斯',
  'b gannon doak': '多克',
  'b gutierrez': '古铁雷斯',
  'b karimov': '卡里莫夫',
  'b mechele': '梅赫勒',
  'b nygren': '尼格伦',
  'b ojeda': '奥赫达',
  'b old': '奥尔德',
  'b rodriguez': '罗德里格斯',
  'b sapoko ndiaye': '恩迪亚耶',
  'b tahirovic': '塔希罗维奇',
  'b thomas asante': '托马斯-阿桑特',
  'b toure': '图雷',
  'b yilmaz': '耶尔马兹',
  'b zeneli': '泽内利',
  'bazoumana toure': '图雷',
  'benchimol': '本希莫尔',
  'benjamin nygren': '尼格伦',
  'benjamin tahirovic': '塔希罗维奇',
  'brandley kuwas': '库瓦斯',
  'brandon thomas asante': '托马斯-阿桑特',
  'brian cipenga': '西彭加',
  'c adams': '亚当斯',
  'c arcus': '阿库斯',
  'c bakambu': '巴坎布',
  'c blackman': '布莱克曼',
  'c burgess': '伯吉斯',
  'c chukwuemeka': '丘克乌埃梅卡',
  'c de ketelaere': '德凯特拉雷',
  'charles de ketelaere': '德凯特拉雷',
  'de ketelaere': '德凯特拉雷',
  'c elliot': '埃利奥特',
  'c fassnacht': '法斯纳赫特',
  'c harvey': '哈维',
  'c hernandez': '埃尔南德斯',
  'c inao oulai': '乌莱',
  'c itten': '伊滕',
  'c larin': '拉林',
  'c martinez': '马丁内斯',
  'c mbemba': '姆本巴',
  'c mccowatt': '麦考瓦特',
  'c metcalfe': '梅特卡夫',
  'c pickel': '皮克尔',
  'c riad': '里亚德',
  'c romero': '罗梅罗',
  'c s huerta valera': '韦尔塔',
  'c soyuncu': '瑟云聚',
  'c starfelt': '斯塔费尔特',
  'c talbi': '塔尔比',
  'c uzun': '乌尊',
  'c volpato': '沃尔帕托',
  'c waterman': '沃特曼',
  'c wood': '伍德',
  'c yirenkyi': '伊伦基',
  'callum mccowatt': '麦考瓦特',
  'camilo vargas': '巴尔加斯',
  'carlens arcus': '阿库斯',
  'carlos harvey': '哈维',
  'cesar blackman': '布莱克曼',
  'cesar montes': '蒙特斯',
  'chancel mbemba': '姆本巴',
  'charles pickel': '皮克尔',
  'cho gue sung': '曹圭成',
  'cristian martinez': '马丁内斯',
  'd alaba': '阿拉巴',
  'd bobadilla': '博巴迪利亚',
  'd borges': '博尔赫斯',
  'd bronn': '布龙',
  'd burnic': '布尔尼奇',
  'd cornelius': '科尼利厄斯',
  'd dalot': '达洛特',
  'd doue': '杜埃',
  'd duarte': '杜阿尔特',
  'd etienne': '埃蒂安',
  'd fonville': '丰维尔',
  'd gomez': '戈麦斯',
  'd gul': '居尔',
  'd hadzikadunic': '哈季卡杜尼奇',
  'd jean jacques': '让·雅克',
  'd khamdamov': '哈姆达莫夫',
  'd livramento': '利夫拉门托',
  'd luckassen': '卢卡森',
  'd lukebakio': '卢克巴基奥',
  'd maeda': '前田大然',
  'd malen': '马伦',
  'd moreira': '莫雷拉',
  'd munoz': '穆尼奥斯',
  'd nazon': '纳宗',
  'd ndoye': '恩多耶',
  'd raum': '劳姆',
  'd sanchez': '桑切斯',
  'd simon': '西蒙',
  'd sow': '索乌',
  'd spence': '斯彭斯',
  'd svensson': '斯文松',
  'd upamecano': '乌帕梅卡诺',
  'd visinsky': '维辛斯基',
  'd wolfe': '沃尔夫',
  'd zima': '齐马',
  'danilo': '达尼洛',
  'danilo santos': '达尼洛',
  'denis zakaria': '扎卡里亚',
  'derek cornelius': '科尼利厄斯',
  'derrick luckassen': '卢卡森',
  'deveron fonville': '丰维尔',
  'diego gomez': '戈麦斯',
  'diogo costa': '迪奥戈·科斯塔',
  'duckens nazon': '纳宗',
  'e achouri': '阿舒里',
  'e alvarez': '阿尔瓦雷斯',
  'e anderson': '安德森',
  'e ashour': '阿舒尔',
  'e bajraktarevic': '巴伊拉克塔雷维奇',
  'e davis': '戴维斯',
  'e demirovic': '德米罗维奇',
  'e dzeko': '哲科',
  'e elmali': '埃尔马勒',
  'e eze': '埃泽',
  'e guessand': '盖桑',
  'e haddad': '哈达德',
  'e hajsafi': '哈吉萨菲',
  'e just': '贾斯特',
  'e kayembe': '卡延贝',
  'e lira': '利拉',
  'e mahmic': '马赫米奇',
  'e makgopa': '马克戈帕',
  'e mendy': '门迪',
  'e nuamah': '努阿马',
  'e owusu': '奥乌苏',
  'e saad': '萨阿德',
  'e shomurodov': '绍穆罗多夫',
  'e skhiri': '斯希里',
  'e stroud': '斯特劳德',
  'e wahi': '瓦希',
  'eberechi eze': '埃泽',
  'ederson': '埃德森',
  'ehsan hajsafi': '哈吉萨菲',
  'elliot anderson': '安德森',
  'elye wahi': '瓦希',
  'endrick': '恩德里克',
  'eom ji sung': '严志成',
  'ernest nuamah': '努阿马',
  'f al buraikan': '布赖坎',
  'f aursnes': '奥斯内斯',
  'f balogun': '巴洛贡',
  'f bjorkan': '比约坎',
  'f chaouat': '沙瓦特',
  'f conceicao': '孔塞桑',
  'f curtis': '柯蒂斯',
  'f de vries': '德弗里斯',
  'f ghedjemis': '盖杰米斯',
  'f grillitsch': '格里利奇',
  'f kadioglu': '卡迪奥卢',
  'f kessie': '凯西',
  'f mayele': '马耶莱',
  'f medina': '梅迪纳',
  'f muslera': '穆斯莱拉',
  'f nmecha': '恩梅查',
  'f pierrot': '皮埃罗',
  'f rieder': '里德尔',
  'f sayfiev': '赛菲耶夫',
  'f surman': '瑟曼',
  'f vinas': '比尼亚斯',
  'fabian balbuena': '巴尔布埃纳',
  'fabinho': '法比尼奥',
  'facundo medina': '梅迪纳',
  'fares chaibi': '沙伊比',
  'felix torres': '托雷斯',
  'findlay curtis': '柯蒂斯',
  'frantzdy pierrot': '皮埃罗',
  'g alfaro': '阿尔法罗',
  'g avalos': '阿瓦洛斯',
  'g caballero': '卡瓦列罗',
  'g doue': '盖拉·杜埃',
  'g gomez': '古斯塔沃·戈麦斯',
  'g gudmundsson': '古德蒙松',
  'g kalulu': '卡卢卢',
  'g kastaneer': '卡斯塔内尔',
  'g konan': '科南',
  'g lo celso': '洛塞尔索',
  'g martinelli': '马丁内利',
  'g martinez': '马丁内斯',
  'g montiel': '蒙铁尔',
  'g mora': '莫拉',
  'g nilsson': '尼尔森',
  'g ochoa': '奥乔亚',
  'g puerta': '普埃尔塔',
  'g reyna': '雷纳',
  'g rodrigues': '罗德里格斯',
  'g roemeratoe': '鲁默拉托',
  'g simeone': '西蒙尼',
  'g til': '蒂尔',
  'g varela': '巴雷拉',
  'g velazquez': '贝拉斯克斯',
  'g yassine': '亚辛',
  'gabriel': '加布里埃尔',
  'gavi': '加维',
  'gervane kastaneer': '卡斯塔内尔',
  'giovani lo celso': '洛塞尔索',
  'gonzalo plata': '普拉塔',
  'gue sung cho': '曹圭成',
  'h abdelkarim': '阿卜杜勒卡里姆',
  'h abdelmaguid': '阿卜杜勒马吉德',
  'h abu dahab': '阿布达哈卜',
  'h al haydos': '海多斯',
  'h ali': '阿里',
  'h aouar': '奥瓦尔',
  'h boudaoui': '布达维',
  'h diarra': '迪亚拉',
  'h falchener': '法尔切纳',
  'h fathy': '法蒂',
  'h kanaani': '卡纳尼',
  'h mastouri': '马斯图里',
  'h mejbri': '梅杰布里',
  'h tabakovic': '塔巴科维奇',
  'h tambakti': '坦巴克提',
  'h vanaken': '范阿肯',
  'h varela': '瓦雷拉',
  'h wright': '赖特',
  'habib diarra': '迪亚拉',
  'hwang hee chan': '黄喜灿',
  'i adel': '阿德尔',
  'i basic': '巴希奇',
  'i bayesh': '巴耶什',
  'i diaz': '迪亚斯',
  'i diop': '迪奥普',
  'i fatawu': '法塔乌',
  'i gharbi': '加尔比',
  'i hien': '希恩',
  'i jakobs': '雅各布斯',
  'i kahveci': '卡赫维奇',
  'i kone': '科内',
  'i matanovic': '马塔诺维奇',
  'i maza': '马扎',
  'i mbaye': '姆巴耶',
  'i perisic': '佩里西奇',
  'i pitta': '皮塔',
  'i rayners': '雷纳斯',
  'i reyes': '雷耶斯',
  'i sangare': '桑加雷',
  'i sergeev': '谢尔盖耶夫',
  'i sunjic': '顺伊奇',
  'i thiago': '蒂亚戈',
  'i yuksek': '于克塞克',
  'ibanez': '伊巴涅斯',
  'inaki williams': '威廉姆斯',
  'issa diop': '迪奥普',
  'j adams': '亚当斯',
  'j adjetey': '阿杰泰',
  'j alcivar': '阿尔西瓦尔',
  'j alonso': '阿隆索',
  'j antonisse': '安东尼斯',
  'j arias': '阿里亚斯',
  'j ayew': '阿尤',
  'j bacuna': '巴库纳',
  'j bell': '贝尔',
  'j bellegarde': '贝勒加德',
  'j bos': '博斯',
  'j cabral': '卡布拉尔',
  'j caceres': '卡塞雷斯',
  'j caicedo': '凯塞多',
  'j campaz': '坎帕斯',
  'j canale': '卡纳莱',
  'j cancelo': '坎塞洛',
  'j casimir': '卡西米尔',
  'j castrop': '卡斯特罗普',
  'j cordoba': '科尔多瓦',
  'j duverne': '迪韦纳',
  'j enciso': '恩西索',
  'j fajardo': '法哈多',
  'j gaber': '加贝尔',
  'j gallardo': '加利亚多',
  'j geria': '杰里亚',
  'j gutierrez': '古铁雷斯',
  'j gvardiol': '格瓦迪奥尔',
  'j hadjam': '哈贾姆',
  'j hassan': '哈桑',
  'j hato': '哈托',
  'j hauge': '豪格',
  'j henderson': '亨德森',
  'j irvine': '厄温',
  'j iskanderov': '伊斯坎德罗夫',
  'j italiano': '伊塔利亚诺',
  'j ito': '伊东纯也',
  'j karlstrom': '卡尔斯特伦',
  'j kayembe': '卡延贝',
  'j kluivert': '克鲁伊维特',
  'j kounde': '孔德',
  'j larsen': '拉森',
  'j lerma': '莱尔马',
  'j leweling': '莱韦林',
  'j locadia': '洛卡迪亚',
  'j lopez': '洛佩斯',
  'j lukic': '卢基奇',
  'j margaritha': '马加里塔',
  'j mateta': '马特塔',
  'j mcginn': '麦金',
  'j monteiro': '蒙泰罗',
  'j nagelsmann': '纳格尔斯曼',
  'j neves': '内维斯',
  'j ordonez': '奥尔多涅斯',
  'j osorio': '奥索里奥',
  'j p van hecke': '范赫克',
  'j porozo': '波罗索',
  'j quansah': '夸恩萨',
  'j quinones': '基尼奥内斯',
  'j quintero': '金特罗',
  'j ramos': '拉莫斯',
  'j randall': '兰德尔',
  'j rodriguez': '罗德里格斯',
  'j ryerson': '里尔森',
  'j sanabria': '胡安·萨纳夫里亚',
  'j sanchez': '豪尔赫·桑切斯',
  'j scally': '斯卡利',
  'j shaffelburg': '沙夫尔堡',
  'j stanisic': '斯塔尼希奇',
  'j suzuki': '铃木淳之介',
  'j tah': '塔',
  'j urozov': '乌罗佐夫',
  'j yeboah': '耶博阿',
  'j zeleny': '泽莱尼',
  'jackson porozo': '波罗索',
  'jacob italiano': '伊塔利亚诺',
  'james rodriguez': '哈梅斯·罗德里格斯',
  'jassem gaber abdulsallam': '加贝尔',
  'jean michael seri': '塞里',
  'john yeboah': '耶博阿',
  'jordan pickford': '皮克福德',
  'jordy alcivar': '阿尔西瓦尔',
  'jordy caicedo': '凯塞多',
  'jose canale': '卡纳莱',
  'jose cordoba': '科尔多瓦',
  'josue casimir': '卡西米尔',
  'junior alonso': '阿隆索',
  'junya ito': '伊东纯也',
  'k akturkoglu': '阿克图尔科卢',
  'k al ghannam': '甘纳姆',
  'k alajbegovic': '阿拉伊贝戈维奇',
  'k alizhonov': '阿利容诺夫',
  'k ayhan': '艾汉',
  'k boudiaf': '布迪亚夫',
  'k castano': '卡斯塔尼奥',
  'k danso': '丹索',
  'k gorre': '戈雷',
  'k goto': '后藤启介',
  'k hafez': '哈菲兹',
  'k itakura': '板仓滉',
  'k koulibaly': '库利巴利',
  'k laimer': '莱默',
  'k lenini': '莱尼尼',
  'k mclean': '麦克莱恩',
  'k nakamura': '中村敬斗',
  'k ogawa': '小川航基',
  'k paez': '帕埃斯',
  'k peprah': '佩普拉',
  'k rodriguez': '罗德里格斯',
  'k sano': '佐野海舟',
  'k sebelebele': '塞贝莱贝莱',
  'k sema': '塞马',
  'k shiogai': '盐贝健人',
  'k sibo': '西博',
  'k sulemana': '苏莱曼纳',
  'k thorstvedt': '托尔斯特韦特',
  'k tierney': '蒂尔尼',
  'k yakob': '雅各布',
  'kaku': '卡库',
  'kenny mclean': '麦克莱恩',
  'kim jin gyu': '金振奎',
  'kim moon hwan': '金文奂',
  'kojo peprah oppong': '佩普拉',
  'konrad laimer': '莱默',
  'l ati zigi': '齐吉',
  'l bergvall': '伯格瓦尔',
  'l cacace': '卡卡切',
  'l camara': '卡马拉',
  'l cerv': '切尔夫',
  'l chavez': '查韦斯',
  'l comenencia': '科梅嫩西亚',
  'l de fougerolles': '德富热罗勒',
  'l deedson': '迪德森',
  'l diaz': '路易斯·迪亚斯',
  'l digne': '迪涅',
  'l duarte': '拉罗斯·杜阿尔特',
  'l dykes': '戴克斯',
  'l foster': '福斯特',
  'l goretzka': '格雷茨卡',
  'l jaquez': '雅克斯',
  'l joseph': '约瑟夫',
  'l krejci': '克雷伊奇',
  'l millar': '米勒',
  'l ostigard': '厄斯蒂高',
  'l paredes': '帕雷德斯',
  'l provod': '普罗沃德',
  'l romo': '罗莫',
  'l shankland': '尚克兰',
  'l sucic': '苏契奇',
  'l trossard': '特罗萨德',
  'l vuskovic': '武什科维奇',
  'leandro paredes': '帕雷德斯',
  'lee jae sung': '李在城',
  'lee kang in': '李刚仁',
  'liam millar': '米勒',
  'luc de fougerolles': '德富热罗勒',
  'lucas bergvall': '伯格瓦尔',
  'lucas mendes': '门德斯',
  'm abdelmonem': '阿卜杜勒莫奈姆',
  'm abu al shamat': '沙马特',
  'm abu hasheesh': '阿布哈希什',
  'm abu taha': '阿布塔哈',
  'm abualnadi': '阿布纳迪',
  'm abunada': '阿布纳达',
  'm aebischer': '埃比舍尔',
  'm akliouche': '阿克利乌什',
  'm al daoud': '达乌德',
  'm al harbi': '哈尔比',
  'm al juwayr': '朱瓦伊尔',
  'm al mannai': '曼奈',
  'm al mardi': '马尔迪',
  'm almiron': '阿尔米隆',
  'm amoura': '阿穆拉',
  'm arnautovic': '阿尔瑙托维奇',
  'm attia': '阿提亚',
  'm baturina': '巴图里纳',
  'm belhadj': '贝勒哈吉',
  'm ben hamida': '本哈米达',
  'm ben ouanes': '本瓦内斯',
  'm bombito': '邦比托',
  'm boxall': '博克萨尔',
  'm chavez garcia': '查韦斯',
  'm choiniere': '舒瓦尼耶',
  'm chytil': '希蒂尔',
  'm de cuyper': '德库珀',
  'm de roon': '德罗恩',
  'm diaw': '迪奥',
  'm diouf': '迪乌夫',
  'm doski': '多斯基',
  'm elia': '埃利亚',
  'm farji': '法尔吉',
  'm fernandez pardo': '费尔南德斯-帕尔多',
  'm friedl': '弗里德尔',
  'm galarza': '加拉萨',
  'm ghaedi': '加埃迪',
  'm gregoritsch': '格雷戈里奇',
  'm guehi': '盖伊',
  'm gusto': '古斯托',
  'm hany': '哈尼',
  'm kanno': '坎诺',
  'm kovacic': '科瓦契奇',
  'm lasheen': '拉欣',
  'm leckie': '莱基',
  'm llorente': '略伦特',
  'm mohammadi': '穆罕默迪',
  'm mohebi': '莫赫比',
  'm muheim': '穆海姆',
  'm muldur': '穆尔杜尔',
  'm niakhate': '尼亚卡特',
  'm nunes': '努涅斯',
  'm pasalic': '帕萨利奇',
  'm pedersen': '佩德森',
  'm rogers': '罗杰斯',
  'm saadoon': '萨敦',
  'm saber': '萨贝尔',
  'm sabitzer': '扎比策尔',
  'm sadilek': '萨迪莱克',
  'm stamenic': '斯塔梅尼奇',
  'm svanberg': '斯万贝里',
  'm tamari': '塔马里',
  'm taremi': '塔雷米',
  'm thiaw': '蒂亚乌',
  'm thorsby': '托尔斯比',
  'm tillman': '蒂尔曼',
  'm torabi': '托拉比',
  'm toure': '图雷',
  'm ugarte': '乌加特',
  'm van de ven': '范德芬',
  'm vina': '比尼亚',
  'm younis': '尤尼斯',
  'm ziko': '齐科',
  'mahmud abunada': '阿布纳达',
  'malick thiaw': '蒂亚乌',
  'maximilian beier': '拜尔',
  'meme': '梅梅',
  'michael gregoritsch': '格雷戈里奇',
  'micky van de ven': '范德芬',
  'miguel almiron': '阿尔米隆',
  'n ake': '阿克',
  'n al dawsari': '多萨里',
  'n al rashdan': '拉什丹',
  'n al rawabdeh': '拉瓦布德',
  'n amiri': '阿米里',
  'n angulo': '安古洛',
  'n benbouali': '本布阿里',
  'n bentaleb': '本塔莱布',
  'n boushal': '布沙尔',
  'n brown': '布朗',
  'n da costa': '达科斯塔',
  'n de la cruz': '德拉克鲁斯',
  'n el aynaoui': '埃纳维',
  'n gonzalez': '冈萨雷斯',
  'n irankunda': '伊兰昆达',
  'n jackson': '杰克逊',
  'n katic': '卡蒂奇',
  'n lang': '朗',
  'n madueke': '马杜埃凯',
  'n mazraoui': '马兹拉维',
  'n mbuku': '姆布库',
  'n mendes': '努诺·门德斯',
  'n molina': '莫利纳',
  'n mukau': '穆考',
  'n patterson': '帕特森',
  'n paz': '帕斯',
  'n pepe': '佩佩',
  'n raskin': '拉斯金',
  'n sadiki': '萨迪基',
  'n semedo': '塞梅多',
  'n sigur': '西居尔',
  'n tagliafico': '塔利亚菲科',
  'n velupillay': '韦卢皮莱',
  'n vlasic': '弗拉希奇',
  'n woltemade': '沃尔特马德',
  'nelson semedo': '塞梅多',
  'nico elvedi': '埃尔维迪',
  'nico o\'reilly': '奥赖利',
  'nicolas otamendi': '奥塔门迪',
  'nikola vlasic': '弗拉希奇',
  'nkosinathi sibisi': '西比西',
  'noor al rawabdeh': '拉瓦布德',
  'o al fakhouri': '法胡里',
  'o alderete': '阿尔德雷特',
  'o appollis': '阿波利斯',
  'o aydin': '艾登',
  'o bobb': '博布',
  'o diakite': '迪亚基特',
  'o khamrobekov': '哈姆罗别科夫',
  'o kokcu': '科克丘',
  'o kossounou': '科苏努',
  'o marmoush': '马尔穆什',
  'o pineda': '皮内达',
  'o rekik': '雷基克',
  'o shukurov': '舒库罗夫',
  'o urunov': '乌鲁诺夫',
  'o vargas': '巴尔加斯',
  'o watkins': '沃特金斯',
  'odiljon khamrobekov': '哈姆罗别科夫',
  'oh hyeon gyu': '吴贤揆',
  'orjan nyland': '尼兰',
  'oumar diakite': '迪亚基特',
  'p adu': '阿杜',
  'p berg': '贝里',
  'p ciss': '西斯',
  'p david': '戴维',
  'p estupinan': '埃斯图皮尼安',
  'p hincapie': '因卡皮耶',
  'p m sarr': '萨尔',
  'p musa': '穆萨',
  'p mwene': '姆韦内',
  'p okon engstler': '奥孔-恩格斯特勒',
  'p schick': '希克',
  'p sucic': '苏契奇',
  'p sulc': '舒尔茨',
  'p wanner': '万纳',
  'p wimmer': '维默',
  'paik seung ho': '白升浩',
  'park jin seob': '朴镇燮',
  'pascal gross': '格罗斯',
  'pervis estupinan': '埃斯图皮尼安',
  'petar sucic': '苏契奇',
  'prince kwabena adu': '阿杜',
  'q timber': '廷贝尔',
  'r aguirre': '阿吉雷',
  'r ait nouri': '艾特努里',
  'r ashurmatov': '阿舒尔马托夫',
  'r belghali': '贝尔加利',
  'r cherki': '谢尔基',
  'r christie': '克里斯蒂',
  'r freuler': '弗罗伊勒',
  'r garcia': '加西亚',
  'r gravenberch': '格拉文贝赫',
  'r jimenez': '希门尼斯',
  'r jiyanov': '吉亚诺夫',
  'r khedira': '赫迪拉',
  'r laryea': '拉里亚',
  'r mahrez': '马赫雷斯',
  'r mendes': '瑞安·门德斯',
  'r mofokeng': '莫福肯',
  'r neves': '内维斯',
  'r pepi': '佩皮',
  'r providence': '普罗维登斯',
  'r rabia': '拉比亚',
  'r rangel': '兰赫尔',
  'r rezaeian': '雷扎伊安',
  'r rios': '里奥斯',
  'r rodriguez': '里卡多·罗德里格斯',
  'r schmid': '施密德',
  'r sosa': '索萨',
  'r stewart': '斯图尔特',
  'r sulaka': '苏拉卡',
  'r thomas': '托马斯',
  'r van eijma': '范艾马',
  'r zerrouki': '泽鲁基',
  'rafik belghali': '贝尔加利',
  'rahman baba': '巴巴',
  'ramiz zerrouki': '泽鲁基',
  'rani khedira': '赫迪拉',
  'roger ibanez': '伊巴涅斯',
  'rustam ashurmatov': '阿舒尔马托夫',
  's abdulhamid': '阿卜杜勒哈米德',
  's adingra': '阿丁格拉',
  's al brake': '布拉克',
  's al dawsari': '多萨里',
  's al rosan': '罗桑',
  's arias': '阿里亚斯',
  's banza': '班扎',
  's barbarez': '巴尔巴雷斯',
  's bazdar': '巴兹达尔',
  's berge': '贝尔格',
  's berhalter': '贝哈尔特',
  's chergui': '谢尔吉',
  's dest': '德斯特',
  's el mourabet': '穆拉贝特',
  's esanov': '埃萨诺夫',
  's eustaquio': '厄斯塔基奥',
  's ezatolahi': '埃扎托拉希',
  's fofana': '福法纳',
  's ghoddos': '戈杜斯',
  's gimenez': '希门尼斯',
  's hansen': '汉森',
  's hardani': '哈尔达尼',
  's kalajdzic': '卡拉伊季奇',
  's khalilzadeh': '哈利勒扎德',
  's kolasinac': '科拉希纳茨',
  's langas': '兰加斯',
  's lopes cabral': '卡布拉尔',
  's machino': '町野修斗',
  's mandash': '曼达什',
  's moghanlou': '莫甘卢',
  's moreira': '莫雷拉',
  's moutoussamy': '穆图萨米',
  's nasrullaev': '纳斯鲁拉耶夫',
  's obaid': '奥贝德',
  's ozcan': '厄兹詹',
  's posch': '波施',
  's radeljic': '拉代利奇',
  's rahimi': '拉希米',
  's rochet': '罗谢',
  's singh': '辛格',
  's taniguchi': '谷口彰悟',
  's tounekti': '图内克蒂',
  's widmer': '维德默',
  'samu costa': '科斯塔',
  'samuel moutoussamy': '穆图萨米',
  'santiago arias': '阿里亚斯',
  'seko fofana': '福法纳',
  'seol young woo': '薛英佑',
  'seung ho paik': '白升浩',
  'shararh': '沙拉尔',
  'sherzod nasrullaev': '纳斯鲁拉耶夫',
  'shurandy sambo': '桑博',
  'siphephelo sithole': '西托莱',
  'sphephelo sithole': '西托莱',
  'stefan posch': '波施',
  't aasgaard': '奥斯戈',
  't ali': '阿里',
  't almada': '阿尔马达',
  't arcanjo': '阿尔坎若',
  't bindon': '宾登',
  't bongonda': '邦贡达',
  't buchanan': '布坎南',
  't castagne': '卡斯塔涅',
  't chong': '钟塔西',
  't chory': '霍里',
  't heggem': '赫格姆',
  't hernandez': '特奥·埃尔南德斯',
  't holes': '霍莱什',
  't koopmeiners': '科普迈纳斯',
  't kubo': '久保建英',
  't maseko': '马塞科',
  't mbatha': '姆巴塔',
  't meunier': '默尼耶',
  't mokoena': '莫科埃纳',
  't moremi': '莫雷米',
  't oluwaseyi': '奥卢瓦塞伊',
  't payne': '佩恩',
  't reijnders': '赖因德斯',
  't rodriguez': '罗德里格斯',
  't soucek': '索切克',
  't tomiyasu': '富安健洋',
  't watanabe': '渡边刚',
  't weah': '维阿',
  't yengi': '延吉',
  't zwane': '兹瓦内',
  'tajon buchanan': '布坎南',
  'thalente mbatha': '姆巴塔',
  'themba zwane': '兹瓦内',
  'tomas araujo': '阿劳霍',
  'trezeguet': '特雷泽盖',
  'trincao': '特林康',
  'tyler adams': '亚当斯',
  'v barco': '巴尔科',
  'v coufal': '库法尔',
  'v darida': '达里达',
  'v lindelof': '林德勒夫',
  'w anton': '安东',
  'w isidor': '伊西多尔',
  'w pina': '皮纳',
  'w semedo': '塞梅多',
  'w singo': '辛戈',
  'w weghorst': '韦霍斯特',
  'wout weghorst': '韦霍斯特',
  'x schlager': '施拉格尔',
  'xaver schlager': '施拉格尔',
  'y abdurisag': '阿卜杜里萨格',
  'y akgun': '阿克贡',
  'y al arab': '阿拉卜',
  'y amyn': '阿明',
  'y ayari': '阿亚里',
  'y barcenas': '巴塞纳斯',
  'y bounou': '布努',
  'y diomande': '迪奥曼德',
  'y fortune': '福琼',
  'y ibrahim': '易卜拉欣',
  'y medina': '梅迪纳',
  'y nagatomo': '长友佑都',
  'y pino': '皮诺',
  'y semedo': '塞梅多',
  'y sugawara': '菅原由势',
  'y suzuki': '铃木唯人',
  'y tielemans': '蒂勒曼斯',
  'y valery': '瓦莱里',
  'y wissa': '维萨',
  'yang hyun jun': '梁贤准',
  'yunus akgun': '阿克贡',
  'z amdouni': '阿姆杜尼',
  'z belaid': '贝莱德',
  'z celik': '切利克',
  'z iqbal': '伊克巴尔',
  'z ismaeel': '伊斯梅尔',
  'z tahseen': '塔赫辛',
  'zaid tahseen': '塔赫辛',
};

export function lookupPlayerZh(raw: string): string | null {
  if (!raw) return null;
  const key = normalizeName(raw);
  if (!key) return null;
  return PLAYER_ZH[key] ?? PLAYER_ZH_FULL[key] ?? null;
}

/*
 * ===== 测试断言示例(可转成单测) =====
 * lookupPlayerZh('L. Messi')            === '梅西'
 * lookupPlayerZh('Kylian Mbappé')       === '姆巴佩'
 * lookupPlayerZh('O. Dembélé')          === '登贝莱'
 * lookupPlayerZh('E. Haaland')          === '哈兰德'
 * lookupPlayerZh('Vinícius Júnior')     === '维尼修斯'
 * lookupPlayerZh('Hakan Çalhanoğlu')    === '恰尔汗奥卢'
 * lookupPlayerZh('M. Ødegaard')         === '厄德高'
 * lookupPlayerZh('Kenan Yıldız')        === '耶尔德兹'
 * lookupPlayerZh('Idrissa Gana Gueye')  === '加纳·盖耶'
 * lookupPlayerZh('Son Heung-min')       === '孙兴慜'
 * lookupPlayerZh('完全不认识的人')        === null
 */
